### ISSUE TITLE
New modifier: 'OnlyRequired'

### ISSUE THREAD

**Issue by jycouet** [gabotechs/graphqxl#46]
Great repo!

I would love to see something like:

<table>
    <thead>
        <tr>
            <th>
                Source GraphQXL
            </th>
            <th>
                Compiled GraphQL
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> 

```graphql
type _MyType {
    foo: String
    bar: String!
}

input MyTypeCreateFields = OnlyRequired<_MyType>

input MyTypeUpdateFields = Optional<_MyType>

                                         #GraphQXL
```
</td><td>

```graphql
input MyTypeCreateFields {
    bar: String!
}

input MyTypeUpdateFields {
    foo: String
    bar: String
}
                               #GraphQL
```
</td></tr></tbody></table>

(maybe there is a better name, but I like quite a lot the idea)

**Comment by gabotechs** [comment]
looks useful, but I don't find any use case that could not be handled by the current syntax.

Your example using the current syntax would look like this:

<table>
    <thead>
        <tr>
            <th>
                Source GraphQXL
            </th>
            <th>
                Compiled GraphQL
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> 

```graphql
type MyTypeCreateFields {
    bar: String!
}

input MyTypeUpdateFields {
    foo: String
    ...Optional<MyTypeCreateFields>
}

                                         #GraphQXL
```
</td><td>

```graphql
input MyTypeCreateFields {
    bar: String!
}

input MyTypeUpdateFields {
    foo: String
    bar: String
}

                               #GraphQL
```
</td></tr></tbody></table>

Do you think this would fit for you?

**Comment by jycouet** [comment]
I would like the 3 _things_ to be present on the right side: `type` `input create` `input update`

Something like: 

<table>
    <thead>
        <tr>
            <th>
                Source GraphQXL
            </th>
            <th>
                Compiled GraphQL
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> 

```graphql
type _MyType {
    foo: String
    bar: String!
}

input MyTypeCreateFields = OnlyRequired<_MyType>

input MyTypeUpdateFields = Optional<_MyType>

                                         #GraphQXL
```
</td><td>

```graphql
type _MyType {
    foo: String
    bar: String!
}

input MyTypeCreateFields {
    bar: String!
}

input MyTypeUpdateFields {
    foo: String
    bar: String
}
                               #GraphQL
```
</td></tr></tbody></table>

I'm not sure that the syntax you propose will allow this. No?

**Comment by gabotechs** [comment]
You could accomplish that with:

<table>
    <thead>
        <tr>
            <th>
                Source GraphQXL
            </th>
            <th>
                Compiled GraphQL
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> 

```graphql
type _OptionalFields {
    foo: String
}

type _RequiredFields {
    bar: String!
}

type MyType {
    ..._OptionalFields
    ..._RequiredFields
}

input MyTypeCreateFields {
    ..._RequiredFields
}

input MyTypeUpdateFields {
    ..._OptionalFields
    ...Optional<_RequiredFields>
}
                                         #GraphQXL
```
</td><td>

```graphql
type _MyType {
    foo: String
    bar: String!
}

input MyTypeCreateFields {
    bar: String!
}

input MyTypeUpdateFields {
    foo: String
    bar: String
}








                               #GraphQL
```
</td></tr></tbody></table>

Even though it is slightly more verbose, you get the same level of reuse by adding fields just to the top level private types.

Note that the `_` prefix is used for hiding blocks from the compiled GraphQL, if you want to override that behaviour that can be configured with the `--private-prefix` flag

**Comment by jycouet** [comment]
Thx for the "_" notice 👍

For the rest, ok, I will not use this approach. Thx for your time.
