### ISSUE TITLE
Production Readiness 

### ISSUE THREAD

**Issue by sandeep14-singh** [gabotechs/graphqxl#53]
Hi , 
I did not get any discussion forum here or in stackoverflow regarding graphqxl, so, i had to create this issue to understand few things. We were inclined to use this in one of our enterprise application and hence want to get clarification w.r.t few things - 

1. "README" says "There is a WIP version of the GraphQXL book with some useful docs".  Is this project WIP ? If yes, what all features are not yet present and when can we expect them to be there
2. Is this project being run/owned/maintained by some org ? Any documentation/references around it would be very helpful. 
3. What is the future roadmap for this project ? Will there be more contributors ? Will this be continuously maintained - like being compatible with federation, integration with other tooling etc ? 

Some clarity on above question would really help in our evaluation.

**Comment by gabotechs** [comment]
> Is this project WIP ? If yes, what all features are not yet present and when can we expect them to be there

The docs are currently in a WIP state, they provide the basic to get started but they could be more complete. The GraphQXL compiler is not in a WIP state, it's ready to use, but it's likely that some niche features of GraphQL are still not supported.

> Is this project being run/owned/maintained by some org?

Right now, it's run just by me as an individual, there's no org involved so far, although I'm open to contributions.

>  What is the future roadmap for this project ?

The current state of the project already addresses the problems that it was targeting, so there's not a defined roadmap for implementing missing pieces or solving known bugs.

> Will there be more contributors ?

Contributions are always welcome, I'm available for reviewing PRs, but currently there's not any open contribution to be addressed.

>  Will this be continuously maintained - like being compatible with federation, integration with other tooling etc ?

Until further notice, yes, I'm available for implementing new features if they're needed. I actually recently merged a PR for making it compatible with Apollo Federation.
