### ISSUE TITLE
Support empty Query, Mutation, etc.

### ISSUE THREAD

**Issue by RobertVillalba** [gabotechs/graphqxl#58]
I have multiple files with each extending the Query type and a base file with an empty Query.

```
# base.graphqxl

import "things"

type Query
```
```
# things.graphqxl

extend type Query {
  getThings: [Thing!]!
}

...
```
When running the generator I get
```
Error: Could not parse GraphQXL spec:

 --> 9:1
  |
9 | type Mutation {}
  | ^---
  |
  = expected type_selection_set, implements, directive, or generic
make: *** [Makefile:16: generated/sensorman.gql] Error 1
```

**Comment by gabotechs** [comment]
The recommended way of doing this with GraphQXL would be to instead rely on the already existing composition mechanisms, for example:

```graphql
# products.graphqxl

type _ProductsQuery {
  product(id: ID!): Product
  productByName(name: String!): Product
  allProducts: [Product!]!
}
```

```graphql
# users.graphqxl

type _UsersQuery {
  user(id: ID!): User
  userByName(name: String!): User
  allUsers: [User!]!
}
```

```graphql
# main.graphqxl

import 'products'
import 'users'

type Query {
  ..._ProductsQuery
  ..._UsersQuery
}
```

That way, it's very clear and explicit the order of the fields in the final `Query` type.

Take a look at [this example](https://graphqxl-explorer.vercel.app/?code=dHlwZSBQcm9kdWN0IHsKICAgIGZvbzogQm9vbGVhbgp9Cgp0eXBlIF9Qcm9kdWN0c1F1ZXJ5IHsKICBwcm9kdWN0KGlkOiBJRCEpOiBQcm9kdWN0CiAgcHJvZHVjdEJ5TmFtZShuYW1lOiBTdHJpbmchKTogUHJvZHVjdAogIGFsbFByb2R1Y3RzOiBbUHJvZHVjdCFdIQp9Cgp0eXBlIFVzZXIgewogICAgZm9vOiBCb29sZWFuCn0KCnR5cGUgX1VzZXJzUXVlcnkgewogIHVzZXIoaWQ6IElEISk6IFVzZXIKICB1c2VyQnlOYW1lKG5hbWU6IFN0cmluZyEpOiBVc2VyCiAgYWxsVXNlcnM6IFtVc2VyIV0hCn0KCnR5cGUgUXVlcnkgewogIC4uLl9Qcm9kdWN0c1F1ZXJ5CiAgLi4uX1VzZXJzUXVlcnkKfQ==)

**Comment by RobertVillalba** [comment]
Ah that makes perfect sense thank you!
